### PR TITLE
Adding custom analytics for report and supplement download buttons.

### PR DESCRIPTION
**Pull request by juliasolorzano**

### CODE REVIEW

**Comment by rogeruiz** [comment]
We haven't added any JavaScript yet to the project, but do we want to have `onclick` attributes for these buttons? Or should we have them inside of a `assets/scripts/analytics.js` file?

If we do go the route of having an `analytics.js` files then we should use `js-` prefix classes for the selectors on those buttons along with grabbing the [`.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) for the button and prepending `Clicked` to the `ga` call to match what is already in the attribute. This could be useful if we'd like to reuse the `analytics.js` in the future for other buttons.

Looks good to me if we decide to keep just the `onclick=""` attributes for now. :+1: :rocket:

**Comment by juliasolorzano** [comment]
@rogeruiz I like the idea of having an `analytics.js` file instead of having the event occur on the buttons themselves (+ add to ffd-toolkit). My thoughts are that we go ahead and merge this in for now and submit a separate pull request to add this new file. Happy to add in here, but would like to go ahead and get this functionality merged in first and iterate on as we move onward!

**Comment by rogeruiz** [comment]
Sounds good to me @juliaelman ! :+1:

**Comment by rogeruiz** [comment]
Resolves a checklist item for #1

**Pull request merged**
