### PR TITLE
Add missing links

### PR DESCRIPTION
**Pull request by maya**
This adds missing links to the site.

### CODE REVIEW

**Comment by juliasolorzano** [comment]
@maya this adds `//` to the file download when running locally. 

@rogeruiz mentioned updating the `config.toml` to configure it properly to run in both env.

**Comment by maya** [comment]
Ah yes it does, the live reload didn't work when I updated it so I saw a single slash.

**Comment by maya** [comment]
Weird, I thought you commented on a different PR (https://github.com/18F/ffd-microsite/pull/29). Was this intended, @juliaelman?

**Comment by rogeruiz** [comment]
Merging this in for now, and fixing the URLs after #29 and #28 are in master :+1:

**Pull request merged**
